config/routes.rb
Oeno::Application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  
  resources :posts

  resources :contact, :only => [:new, :create]

  root 'static_pages#home'

  match '/about',  to: 'static_pages#about',  via: 'get'
  match '/how_its_done',  to: 'static_pages#how',  via: 'get'
  match '/price_guide',  to: 'static_pages#price',  via: 'get'
  match '/weddings',  to: 'static_pages#weddings',  via: 'get'
  match '/faq',  to: 'static_pages#faq',  via: 'get'
  match '/labels',  to: 'static_pages#labels',  via: 'get'

  

end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :body, :nickname

  validates :name, :email, :body, :presence => true
  validates :email, 
            :format => { :with => /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/ }
  validates :nickname, 
            :format => { :with => /\A\z/ }

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :title, presence: true
  validates :text, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

	def new
    @message = Message.new
  end

  def create
    @message = Message.new(contact_params)
    
    if @message.valid?
      UserMailer.new_message(@message).deliver
      redirect_to(root_path, :notice => "Message was successfully sent.")
    else
      render :new
    end
  end

  private

    def contact_params
      params.require(:message).permit(:name, :email, :body, :nickname)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :verify_is_admin, only: [:new, :create, :edit, :update, :destroy]

	def new
		@post = Post.new
	end

	def create
    @post = Post.new(post_params)
 
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def index
    @posts = Post.all
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
 
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:success] = "Post removed."
    redirect_to posts_path
  end
 
  private

    def post_params
      params.require(:post).permit(:title, :text)
    end
    
    # Before filter(s)

    def verify_is_admin
      (current_user.nil?) ? redirect_to(root_path) : (redirect_to(root_path) unless current_user.admin?)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def how
  end

  def price
  end

  def weddings
  end

  def faq
  end

  def labels
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "oeno winemaking"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      sha = Digest::SHA1.hexdigest(code)
      Rails.cache.fetch ["code", language, sha].join('-') do
        Pygments.highlight(code, lexer: language)
      end
    end
  end

  def markdown(text)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/contact/new.html.erb
<% provide(:title, "Contact") %>
<h2>Let's get in touch</h2>
<p id="contact-inst">Leave a short message and we'll get back to you soon.</p>
<div class="row">
  <div class="span6 offset3">
    <div class="form-wrap">
      <%= form_for @message, :url => new_contact_path do |f| %>
        <% if @message.errors.any? %>
          <div id="error_explanation">
            <div class="alert alert-error">
              The form contains <%= pluralize(@message.errors.count, "error") %>.
            </div>
            <ul>
              <% @message.errors.full_messages.each do |msg| %>
                <li>* <%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="field">
          <%= f.label :name %>
          <%= f.text_field :name %>
        </div>

        <div class="field" style="display: none;">
          <%= f.label :nickname %>
          <%= f.text_field :nickname %>
        </div>
    
        <div class="field">
          <%= f.label :email %>
          <%= f.text_field :email %>
        </div>

        <div class="field">
          <%= f.label :body, "Message" %>
          <%= f.text_area :body, rows: "8" %>
        </div>   

        <%= f.submit "Send", class: "btn btn-primary" %>
       
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<hr />
<div class="row">
  <div class="span6 offset3">
    <div class="address">
      <p>26 Hoolai St. STE. 900</br>
        Kailua, HI  96734</br>
        808.263.6366</br>
        info@oenowinemaking.com
      </p>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">

      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <%= link_to "oeno winemaking", root_path, :class => "brand", :id => "logo" %>
      <div class="nav-collapse collapse">
        <nav>
          <ul class="nav pull-left">
            <li class="<%='active' if current_page?(about_path) %>"><%= link_to 'About', about_path %></li>
            <li class="<%='active' if current_page?(how_its_done_path) %>"><%= link_to "How it's done", how_its_done_path %></li>
            <li class="<%='active' if current_page?(price_guide_path) %>"><%= link_to 'Price Guide', price_guide_path %></li>
            <li class="<%='active' if current_page?(weddings_path) %>"><%= link_to 'Weddings', weddings_path %></li>
            <% if current_user && current_user.admin? %>
              <li class="dropdown <%='active' if current_page?(posts_path) | current_page?(new_post_path) %>">
                <%= link_to 'News <b class="caret"></b>'.html_safe, "#", :data => {:toggle=>"dropdown"}, :class => "dropdown-toggle" %>
                <ul class="dropdown-menu", role="menu" aria-labelledby="dLabel">
                  <li><%= link_to "New Post", new_post_path %></li>
                  <li><%= link_to "All Posts", posts_path %></li>
                </ul>
              </li>
            <% else %>
              <li class="<%='active' if current_page?(posts_path) %>"><%= link_to 'News', posts_path %></li>
            <% end %>
            <li class="<%='active' if current_page?(faq_path) %>"><%= link_to "FAQ's", faq_path %></li>
            <li class="<%='active' if current_page?(new_contact_path) %>"><%= link_to "Contact", new_contact_path %></li>
          </ul>
          <ul class="nav pull-right">
            <% if user_signed_in? %>
              <li id="fat-menu" class="dropdown <%='active' if current_page?(edit_user_registration_path) %>">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
                  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Login", new_user_session_path %></li>
            <% end %>
          </ul>
        </nav>
      </div><!-- end .nav-collapse -->

    </div><!-- end .container -->
  </div><!-- end .navbar-inner -->
</header>

app/views/layouts/_meta.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0">

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/meta' %>
    <%= render 'layouts/shim' %>
    <link rel="icon" href="fav-32.png" sizes="32x32">
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% if !notice.blank? %>
        <p class="notice"><%= notice %></p>
      <% end %>
      <% if !alert.blank? %>
        <p class="alert"><%= alert %></p>
      <% end %>
    	<%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="row">
  <div class="span8 offset2">
    <div class="form-wrap">      
      <h2>Edit post</h2>
       
      <%= form_for :post, url: post_path(@post.id),
      method: :patch do |f| %>
        <% if @post.errors.any? %>
        <div id="errorExplanation">
          <h2><%= pluralize(@post.errors.count, "error") %> prohibited
            this post from being saved:</h2>
          <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
        <% end %>
        <p>
          <%= f.label :title %>
          <%= f.text_field :title %>
        </p><br>
       
        <p>
          <%= f.label :text %>
          <%= f.text_area :text, :rows => "16" %>
        </p><br>
       
        <p>
          <%= f.submit "Edit", class: "btn btn-primary" %>
        </p>
      <% end %>
    </div>
  </div>
</div>
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% provide(:title, "News") %>
<h1 class="blog_title">Oeno Winemaking</h1>
  <% @posts.each do |post| %>
    <h2 class="post_title"><%= post.title %></h2>
    <h3 class="post_time"><%= post.created_at.strftime("%B %d, %Y") %></h3>
    <div class="row">
      <div class="span8 offset2">
        <div class="markdown">
          <%= markdown(post.text) %>
        </div>
      </div>
    </div>

    <div class="show_edit_del_ul">
      <ul>
        <li><%= link_to 'Show More', post_path(post), :class => "btn btn-lo" %></li>
        <% if current_user && current_user.admin? %>
          <li><%= link_to 'Edit', edit_post_path(post), :class => "btn" %></li>
          <li><%= link_to 'Delete Post', post_path(post),
                             method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %></li>
        <% end %>
      </ul>
    </div> 
  <% end %>

  <%#= will_paginate @posts %>

app/views/posts/new.html.erb
 <div class="row">
  <div class="span8 offset2">
    <div class="form-wrap">     
      <h2>New Post</h2>

      <%= form_for :post, url: posts_path do |f| %>
        <% if @post.errors.any? %>
          <div id="errorExplanation">
            <h2><%= pluralize(@post.errors.count, "error") %> prohibited
            this post from being saved:</h2>
            <ul>
              <% @post.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <p>
          <%= f.label :title %>
          <%= f.text_field :title %>
        </p><br>
       
        <p>
          <%= f.label :text %>
          <%= f.text_area :text, :rows => "16" %>
        </p><br>
       
        <p>
          <%= f.submit "Submit", class: "btn btn-primary" %>
        </p>
      <% end %>
    </div>
  </div>
</div>
<%= link_to 'Back', posts_path, class: "btn" %>

app/views/posts/show.html.erb
<% provide(:title, "#{@post.title}") %>
<h1 class="blog_title">L.O. Photography</h1>
<h2 class="post_title"><%= @post.title %></h1>
<h3 class="post_time"><%= @post.created_at.strftime("%B %d, %Y") %></h3>

<div class="row">
  <div class="span8 offset2">
    <div class="markdown">
    	<%= markdown(@post.text) %>
    </div>
  </div>
</div>

<%= link_to 'Back', posts_path, :class => "btn" %>
<% if current_user && current_user.admin? %>
  <%= link_to 'Edit', edit_post_path(@post), :class => "btn" %>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About Us") %>
<div class="row">
	<div class="span8 offset2">
    <h2>Who we are</h2>
    <p>
	    Oeno- (Eeh-No) Is the greek goddess of wine. She had the ability to turn ANYTHING into 
      wine.  Our kind of goddess! 
    </p>
    <p>
    	We first opened our doors for business in September of 2008 in Kailua, HI.  We have a true 
      passion for wine and wanted to share that passion with as many people as we could.   Our goal is to 
      share and spread our enthusiasm for wine with novices to experts, and help facilitate and create an 
      area where people can experience all the facets of wine and winemaking and create their own 
      wonderful custom personalized wine.  Please stop by for a tasting or just to talk about wine.  We 
      learn something new every day and hope all our visitors can pick up a lot or a little knowledge 
      every time they pass through our doors.  Winemaking is a truly historic process and a joy to 
      experience, so no matter what your experience level, come on by and share our enthusiasm for 
      wine with us.
    </p>
    <p class="quote">
        "for drinking: the arrival of a friend; one's present 
        or future thirst; the excellence of the wine; or any 
        other reason."
      </p>
      <p class="author">
        ~Latin saying
      </p>
  </div>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>

app/views/static_pages/faq.html.erb
<% provide(:title, "F.A.Q's") %>
<div class="row faq">
	<div class="span8 offset2">
		<h4>Bottling Party Policies and/or Label Specifications?</h4>
		<p><%= link_to "How it's done", how_its_done_path %><p>
		<h4>How many bottles does a kit make?</h4>
		<p>
			Each kit yields 28-31 bottles. The discrepancies in bottles per kit is due to the amount of sediment in the wine, which will naturally displace 
      the liquid.
    </p>
    <h4>Can I make half a kit?</h4>
    <p>
    	We cannot sell half kits. But if you are interested in taking home a smaller amount of wine, gather a few friends and split it up. The larger the 
      group, the more types of wine you can make and the more you get to try!
    </p>
    <h4>How long does the process take?</h4>
    <p>
    	The mixing process (the first step) takes 15-20 minutes.  This consists of mixing the ingredients included in the wine kit with water in the 
      primary fermenter. 
    </p>
    <p>
    	Fermentation takes 4-6 weeks depending on the type of wine  you purchased.  The Grand Cru, Grand Cru Regional/International, and 
      Orchard Breezin’ wines are 4 or 5 week wines.  The rest are 6-week wines.
	  </p>
	  <p>
	  	After the wine is finished fermenting, you and your party will come in to bottle it and label it.  We encourage the bottling to be a festive time 
      with friends and family.  Bring food and your favorite mp3 playlist and celebrate your creation!
	  </p>
	  <h4>Can I blend kits?</h4>
	  <p>
	  	Blending wines  requires the purchase of two or more wines.  You are more than welcome to blend; however, please be aware that we cannot 
      guarantee the outcome of the wine.
    </p>
    <h4>Do you add sulfites to the wine?</h4>
    <p>
    	We must add sulfites to your wine in order to protect it from spoilage-causing microbes and oxidation.  It must be added, otherwise it will go 
      bad.  Our wines are designed to have 35-50 ppm (parts per million) of sulfite in the finished wine.  This is low compared to commercial wines, 
      which contain up to 70 ppm, or dried fruit like raisins, which can contain up to 250 ppm.  This is part of the reason your wine will mature 
      relatively quickly.  If all or most of your wine will be aged past 12-18 months, ask us about adding additional sulfite.
	  </p>
	  <h4>What else gets added to my wine before bottling?</h4>
	  <p>
	  	On the first day (mixing day), aside from the yeast, you also added bentonite to your juice.  Bentonite is a fining agent.  It helps to clear the 
      sediment out of your wine, and it also works during primary fermentation to help your juice ferment.  Bentonite is a type of clay composed of 
      sodium and calcium.  When used in wine making, it is stirred into the wine to remove proteins and other haze-causing particles.  It attaches 
      itself to a particle and together they are too heavy to stay in suspension.  Bentonite settles out so completely that it does not leave any residue 
      of taste or color behind.
    </p>
    <p>
    	During the stabilizing of your wine, we add sulfite and potassium sorbate.  Sulfite protects the wine from spoilage-causing microbes and
      oxidation.  It must be added, otherwise it will go bad.  Potassium sorbate inhibits the yeast from re-fermenting in the bottle.  If your wine starts 
      to re-ferment in the bottle, gas will build up inside and can push out the cork or burst the bottle.
    </p>
    <p>
    	Fining, or clearing, is established with the use of chitosan and kieselsol. Chitosan is a positively charged agent derived from shellfish.  It 
      adheres to negatively charged tannins and works extremely well in conjunction with kieselsol.  Kieselsol is a 30% solution of silicon dioxide.  It 
      is negatively charged, thereby adhering strongly to positively charged proteins.  When used in conjunction with chitosan, it creates a strong 
      electrostatic charge, brings the bonded particles to the bottom of the carboy, and produces crystal clear wines within 2 weeks.
    </p>
    <h4>When you say “award-winning wines” what do you mean?</h4>
    <p>
    	RJ Spagnols wines have consistently surpassed the competition at the annual WineMaker International Amateur wine competition.  We are 
      proud to boast the quality of wines that we sell!  If you are interested in becoming an amateur competitor and/or learning more about the
      competition, <%= link_to "WineMaker", "http://www.winemakermag.com/competition", target: "_blank" %>
    </p>  
    <h4>Does your pricing include bottles?</h4>
    <p>Yes, our pricing not only includes bottles, but corks, shrink caps, and labels, too!</p>
    <h4>Where does the juice come from?</h4>
    <p>
    	The juice in our RJ Spagnols brand product comes from top-quality vineyards all over the world.  RJ Spagnols contracts to purchase grapes 
      from growers by specifying conditions at harvest.  These specifications tend to be very rigid, for although the grapes may change radically from 
      harvest to harvest, it is essential that the juices maintain very high levels of consistency so you can be sure of what you are purchasing!
    </p>
    <h4>How are the wine kits made?</h4>
    <p><%= link_to "How it's done", how_its_done_path %></p>
    <h4>How long should I age my wine?</h4>
    <p>
    	That depends on the wine.  Generally, higher-end wines need more time to age than more inexpensive wines.  Reds need longer than whites, 
      dry wines need longer than off-dry, and more full-bodied wines need longer than lighter, fruitier wines.  If you can let your wine age for at least 
      a month or two in the bottle, you’ll be surprised by how much it will improve.  The flavor profile of a wine is like an arc.  It will improve over 
      time and reach a peak, and then the quality will start to decline.  One of the great things about kit wine and the 28-31 bottles you take home is 
      that you can consume your wine over time and taste the differences.
    </p>
    <h4>How long will my wine last?</h4>
    <p>
    	Four-week wines will generally last 12-16 months, six-week wines 2-3 years.  If you want to keep most or all of your wine for more than 12 
      months, ask us about adding extra sulfite.  Red wines will typically last longer than whites. And remember, storage is important!
    </p>
    <h4>How should I store my wine?</h4>
    <p>
    	deally, it should be in a dark, humid, cool (55°-60°F) place with little temperature fluctuation and no movement.  If the closest you can come 
      to this is the back of a cupboard or your closet, don’t fret. Since we use synthetic corks, your wine does not have to be stored on its side.  
    </p>
    <h4>Can I store my wine in the fridge?</h4>
    <p>Your refrigerator is not an ideal place to store wine long-term as it is too cool, too dry, and is generally vibrating.</p>
    <h4>Why do you use synthetic corks?</h4>
    <p>
    	Nomacorc© synthetic corks are best for use with our wines for a number of reasons.  First, they allow for freedom in storage as it is not 
      necessary for wine to be stored on its side during aging.  In a climate like Hawaii’s, humidity is a large factor in wine storage.  With synthetic 
      corks, there is no need to worry about shrinkage or contraction of your cork, which would allow the wine to oxidize.  Synthetic corks provide 
      consistent, predictable oxygen management.  As a result, off flavors due to oxidation and reduction or cork taint are a worry of the past. 
    </p>
    <h4>Can I use my own bottles?</h4>
    <p>We definitely welcome the recycling of bottles!  Here are a few guidelines to help you:</p>
    <ol>
    	<li>If you plan on using your own bottles, please let us know before your bottling date!  You will need 28-31 bottles.</li>
    	<li>Make sure you’re using the right kind of bottle. Screw-top bottles are not recommended.  The threads can chip and you cannot be 
          sure of how good a seal you have.  It is also not a good idea to cork a screw-top bottle.  The neck is not as strong as a bottle made for corks 
          and may break.  A standard wine bottle has a neck opening 18.5 mm in diameter.</li>
      <li>Make sure your bottles are clean and sanitary.  Clean bottles won’t have any residue or “gunk” in them.  We recommend to sanitize 
          your bottles just before bottling with a sulfite solution.  This will prevent the growth of any spoilage organisms in the bottle.</li>
    </ol>
	</div>
</div>

app/views/static_pages/home.html.erb
<div class="row">
  <aside class="span2">
    <section>
      <h3>Phone</h3>
      <h4>(808) 263-6366</h4>
      <hr />
      <h3>Hours</h3>
      <h4>Wednesday - Sunday:</h4>
      <h4>11am - 8pm</h4>
      <h4>Closed Monday & Tuesday</h4>
      <hr />
      <h4>OENO Happy Hour!</h4>
      <h4>Wednesday - Friday:</h4>
      <h4>11am - 3pm</h4>
  </section>
  </aside>
  <div class="span10 right">
    <%= image_tag "oeno_logo.png", class: "logo" %>
    <%= image_tag "banner.png", class: "banner" %>
    <h1>taste. create. enjoy.</h1>
    <h2>Now Available!</h2>
    <h2>Oeno Handcrafted Beermaking</h2>
    <p>
      We offer a unique hands-on experience in creating personalized bottles of world class wine.   Your personalized wine 
      is great for gifts, favors, starting or restocking your wine cellar, using as a business promotional tool, or just to have 
      on hand saving you a trip to the store and standing in front of the always overwhelming wine selection.
    </p>
    <p>
      Oeno Handcraft Beermaking is a selection of over 100 different styles of craft beer, handmade for you and ready to 
      be bottled when you return for your party.
    </p>
    <p>
      Our store is perfect for hosting events and parties; whether it's a birthday, anniversary, wedding, business gathering, 
      or just a fun evening out with your friends. 
    </p>
    <p>
      If you are a fan of wine, whether novice or sommelier, come on in and check out our huge selection of wines.  We 
      offer varietals from all over the world, from Pinots to Piesporters, so our wines are sure to please any palate.
    </p>

  </div>
</div>
<div class="row">
  <div class="span2">
  </div>
  <div class="span6 offset2">
    <p class="quote">
      "Wine is one of the most civilized things in the world and one 
      of the most natural things of the world that has been brought to 
      the greatest perfection, and it offers a greater range for 
      enjoyment and appreciation than, possibly, any other purely 
      sensory thing."
    </p>
    <p class="author">
      ~Ernest Hemingway</br>
      Death in the Afternoon
    </p>
  </div>
</div>

app/views/static_pages/labels.html.erb
<% provide(:title, "Labels") %>

app/views/static_pages/weddings.html.erb
<% provide(:title, "Weddings") %>
<div class="row married">
	<div class="span8 offset2">
    <h1>Getting Maried?</h2>
    <h2>Call today to schedule your wine tasting!</h3>
    <h3>your wedding. your wine. your labels.</h3>
    <hr class="hr2" />
    <p>
    	Make the most of your wedding day with exceptional wines that display
      your personal and unique touch. Create and design the perfect wine labels
      to showcase your special day. (Not the creative type? Ask us to help create
      your labels, <i>free of charge.</i>)
    </p>
    <p>
    	With your own label on your own world class wine, our wines are the perfect
    	way to please your geusts at the reception or provide a memorable wedding
    	favor. <i>We do half size bottles as well!</i> for those special individuals
    	you want to thank.
    </p>
    <p>
    	Choose from over 50 wines from our award winning wine list, and be sure to 
    	take advantage of our custom winery where you are able to taste your wines
    	before you purchase them.
    </p>
    <p>
    	Our winery is also the perfect place to host a pre-wedding event. You and 
    	your guests can participate in bottling all your wine to add a truly personalized
    	touch. Bring pupus and, of course, enjoy the fruits of your labor.
    </p>
    <%= image_tag "wedding.jpg" %>

  </div>
</div>